g++ binary/main.cpp binary/inf_binary.cpp binary/io_binary.cpp         -O3 -mcpu=apple-a14 -std=c++11 -lgsl -lgslcblas -o mpl
./mpl -d ../data/simulation/sigmoid -i sequences/sample-0.dat -o output_const/sc-0.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-0.dat -es traitseq.dat -ed traitdis/traitdis-0.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-1.dat -o output_const/sc-1.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-1.dat -es traitseq.dat -ed traitdis/traitdis-1.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-2.dat -o output_const/sc-2.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-2.dat -es traitseq.dat -ed traitdis/traitdis-2.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-3.dat -o output_const/sc-3.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-3.dat -es traitseq.dat -ed traitdis/traitdis-3.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-4.dat -o output_const/sc-4.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-4.dat -es traitseq.dat -ed traitdis/traitdis-4.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-5.dat -o output_const/sc-5.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-5.dat -es traitseq.dat -ed traitdis/traitdis-5.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-6.dat -o output_const/sc-6.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-6.dat -es traitseq.dat -ed traitdis/traitdis-6.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-7.dat -o output_const/sc-7.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-7.dat -es traitseq.dat -ed traitdis/traitdis-7.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-8.dat -o output_const/sc-8.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-8.dat -es traitseq.dat -ed traitdis/traitdis-8.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-9.dat -o output_const/sc-9.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-9.dat -es traitseq.dat -ed traitdis/traitdis-9.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-10.dat -o output_const/sc-10.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-10.dat -es traitseq.dat -ed traitdis/traitdis-10.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-11.dat -o output_const/sc-11.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-11.dat -es traitseq.dat -ed traitdis/traitdis-11.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-12.dat -o output_const/sc-12.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-12.dat -es traitseq.dat -ed traitdis/traitdis-12.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-13.dat -o output_const/sc-13.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-13.dat -es traitseq.dat -ed traitdis/traitdis-13.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-14.dat -o output_const/sc-14.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-14.dat -es traitseq.dat -ed traitdis/traitdis-14.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-15.dat -o output_const/sc-15.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-15.dat -es traitseq.dat -ed traitdis/traitdis-15.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-16.dat -o output_const/sc-16.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-16.dat -es traitseq.dat -ed traitdis/traitdis-16.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-17.dat -o output_const/sc-17.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-17.dat -es traitseq.dat -ed traitdis/traitdis-17.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-18.dat -o output_const/sc-18.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-18.dat -es traitseq.dat -ed traitdis/traitdis-18.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-19.dat -o output_const/sc-19.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-19.dat -es traitseq.dat -ed traitdis/traitdis-19.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-20.dat -o output_const/sc-20.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-20.dat -es traitseq.dat -ed traitdis/traitdis-20.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-21.dat -o output_const/sc-21.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-21.dat -es traitseq.dat -ed traitdis/traitdis-21.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-22.dat -o output_const/sc-22.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-22.dat -es traitseq.dat -ed traitdis/traitdis-22.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-23.dat -o output_const/sc-23.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-23.dat -es traitseq.dat -ed traitdis/traitdis-23.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-24.dat -o output_const/sc-24.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-24.dat -es traitseq.dat -ed traitdis/traitdis-24.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-25.dat -o output_const/sc-25.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-25.dat -es traitseq.dat -ed traitdis/traitdis-25.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-26.dat -o output_const/sc-26.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-26.dat -es traitseq.dat -ed traitdis/traitdis-26.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-27.dat -o output_const/sc-27.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-27.dat -es traitseq.dat -ed traitdis/traitdis-27.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-28.dat -o output_const/sc-28.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-28.dat -es traitseq.dat -ed traitdis/traitdis-28.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-29.dat -o output_const/sc-29.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-29.dat -es traitseq.dat -ed traitdis/traitdis-29.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-30.dat -o output_const/sc-30.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-30.dat -es traitseq.dat -ed traitdis/traitdis-30.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-31.dat -o output_const/sc-31.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-31.dat -es traitseq.dat -ed traitdis/traitdis-31.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-32.dat -o output_const/sc-32.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-32.dat -es traitseq.dat -ed traitdis/traitdis-32.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-33.dat -o output_const/sc-33.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-33.dat -es traitseq.dat -ed traitdis/traitdis-33.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-34.dat -o output_const/sc-34.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-34.dat -es traitseq.dat -ed traitdis/traitdis-34.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-35.dat -o output_const/sc-35.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-35.dat -es traitseq.dat -ed traitdis/traitdis-35.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-36.dat -o output_const/sc-36.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-36.dat -es traitseq.dat -ed traitdis/traitdis-36.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-37.dat -o output_const/sc-37.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-37.dat -es traitseq.dat -ed traitdis/traitdis-37.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-38.dat -o output_const/sc-38.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-38.dat -es traitseq.dat -ed traitdis/traitdis-38.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-39.dat -o output_const/sc-39.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-39.dat -es traitseq.dat -ed traitdis/traitdis-39.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-40.dat -o output_const/sc-40.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-40.dat -es traitseq.dat -ed traitdis/traitdis-40.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-41.dat -o output_const/sc-41.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-41.dat -es traitseq.dat -ed traitdis/traitdis-41.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-42.dat -o output_const/sc-42.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-42.dat -es traitseq.dat -ed traitdis/traitdis-42.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-43.dat -o output_const/sc-43.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-43.dat -es traitseq.dat -ed traitdis/traitdis-43.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-44.dat -o output_const/sc-44.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-44.dat -es traitseq.dat -ed traitdis/traitdis-44.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-45.dat -o output_const/sc-45.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-45.dat -es traitseq.dat -ed traitdis/traitdis-45.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-46.dat -o output_const/sc-46.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-46.dat -es traitseq.dat -ed traitdis/traitdis-46.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-47.dat -o output_const/sc-47.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-47.dat -es traitseq.dat -ed traitdis/traitdis-47.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-48.dat -o output_const/sc-48.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-48.dat -es traitseq.dat -ed traitdis/traitdis-48.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-49.dat -o output_const/sc-49.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-49.dat -es traitseq.dat -ed traitdis/traitdis-49.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-50.dat -o output_const/sc-50.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-50.dat -es traitseq.dat -ed traitdis/traitdis-50.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-51.dat -o output_const/sc-51.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-51.dat -es traitseq.dat -ed traitdis/traitdis-51.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-52.dat -o output_const/sc-52.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-52.dat -es traitseq.dat -ed traitdis/traitdis-52.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-53.dat -o output_const/sc-53.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-53.dat -es traitseq.dat -ed traitdis/traitdis-53.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-54.dat -o output_const/sc-54.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-54.dat -es traitseq.dat -ed traitdis/traitdis-54.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-55.dat -o output_const/sc-55.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-55.dat -es traitseq.dat -ed traitdis/traitdis-55.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-56.dat -o output_const/sc-56.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-56.dat -es traitseq.dat -ed traitdis/traitdis-56.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-57.dat -o output_const/sc-57.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-57.dat -es traitseq.dat -ed traitdis/traitdis-57.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-58.dat -o output_const/sc-58.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-58.dat -es traitseq.dat -ed traitdis/traitdis-58.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-59.dat -o output_const/sc-59.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-59.dat -es traitseq.dat -ed traitdis/traitdis-59.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-60.dat -o output_const/sc-60.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-60.dat -es traitseq.dat -ed traitdis/traitdis-60.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-61.dat -o output_const/sc-61.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-61.dat -es traitseq.dat -ed traitdis/traitdis-61.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-62.dat -o output_const/sc-62.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-62.dat -es traitseq.dat -ed traitdis/traitdis-62.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-63.dat -o output_const/sc-63.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-63.dat -es traitseq.dat -ed traitdis/traitdis-63.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-64.dat -o output_const/sc-64.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-64.dat -es traitseq.dat -ed traitdis/traitdis-64.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-65.dat -o output_const/sc-65.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-65.dat -es traitseq.dat -ed traitdis/traitdis-65.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-66.dat -o output_const/sc-66.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-66.dat -es traitseq.dat -ed traitdis/traitdis-66.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-67.dat -o output_const/sc-67.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-67.dat -es traitseq.dat -ed traitdis/traitdis-67.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-68.dat -o output_const/sc-68.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-68.dat -es traitseq.dat -ed traitdis/traitdis-68.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-69.dat -o output_const/sc-69.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-69.dat -es traitseq.dat -ed traitdis/traitdis-69.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-70.dat -o output_const/sc-70.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-70.dat -es traitseq.dat -ed traitdis/traitdis-70.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-71.dat -o output_const/sc-71.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-71.dat -es traitseq.dat -ed traitdis/traitdis-71.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-72.dat -o output_const/sc-72.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-72.dat -es traitseq.dat -ed traitdis/traitdis-72.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-73.dat -o output_const/sc-73.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-73.dat -es traitseq.dat -ed traitdis/traitdis-73.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-74.dat -o output_const/sc-74.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-74.dat -es traitseq.dat -ed traitdis/traitdis-74.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-75.dat -o output_const/sc-75.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-75.dat -es traitseq.dat -ed traitdis/traitdis-75.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-76.dat -o output_const/sc-76.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-76.dat -es traitseq.dat -ed traitdis/traitdis-76.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-77.dat -o output_const/sc-77.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-77.dat -es traitseq.dat -ed traitdis/traitdis-77.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-78.dat -o output_const/sc-78.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-78.dat -es traitseq.dat -ed traitdis/traitdis-78.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-79.dat -o output_const/sc-79.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-79.dat -es traitseq.dat -ed traitdis/traitdis-79.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-80.dat -o output_const/sc-80.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-80.dat -es traitseq.dat -ed traitdis/traitdis-80.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-81.dat -o output_const/sc-81.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-81.dat -es traitseq.dat -ed traitdis/traitdis-81.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-82.dat -o output_const/sc-82.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-82.dat -es traitseq.dat -ed traitdis/traitdis-82.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-83.dat -o output_const/sc-83.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-83.dat -es traitseq.dat -ed traitdis/traitdis-83.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-84.dat -o output_const/sc-84.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-84.dat -es traitseq.dat -ed traitdis/traitdis-84.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-85.dat -o output_const/sc-85.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-85.dat -es traitseq.dat -ed traitdis/traitdis-85.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-86.dat -o output_const/sc-86.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-86.dat -es traitseq.dat -ed traitdis/traitdis-86.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-87.dat -o output_const/sc-87.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-87.dat -es traitseq.dat -ed traitdis/traitdis-87.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-88.dat -o output_const/sc-88.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-88.dat -es traitseq.dat -ed traitdis/traitdis-88.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-89.dat -o output_const/sc-89.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-89.dat -es traitseq.dat -ed traitdis/traitdis-89.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-90.dat -o output_const/sc-90.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-90.dat -es traitseq.dat -ed traitdis/traitdis-90.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-91.dat -o output_const/sc-91.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-91.dat -es traitseq.dat -ed traitdis/traitdis-91.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-92.dat -o output_const/sc-92.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-92.dat -es traitseq.dat -ed traitdis/traitdis-92.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-93.dat -o output_const/sc-93.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-93.dat -es traitseq.dat -ed traitdis/traitdis-93.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-94.dat -o output_const/sc-94.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-94.dat -es traitseq.dat -ed traitdis/traitdis-94.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-95.dat -o output_const/sc-95.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-95.dat -es traitseq.dat -ed traitdis/traitdis-95.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-96.dat -o output_const/sc-96.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-96.dat -es traitseq.dat -ed traitdis/traitdis-96.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-97.dat -o output_const/sc-97.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-97.dat -es traitseq.dat -ed traitdis/traitdis-97.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-98.dat -o output_const/sc-98.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-98.dat -es traitseq.dat -ed traitdis/traitdis-98.dat
./mpl -d ../data/simulation/sigmoid -i sequences/sample-99.dat -o output_const/sc-99.dat -g 1 -N 1e3 -mu 1e-3 -rr 1e-3 -e traitsite/traitsite-99.dat -es traitseq.dat -ed traitdis/traitdis-99.dat
